/**
 * Asian cuisine keywords used when the parsed query cuisine type is "asian"
 * (see matchesSingleCuisineType in matchers).
 */
export const ASIAN_CUISINES = [
  'japanese',
  'chinese',
  'korean',
  'thai',
  'vietnamese',
  'indian',
  'ramen',
  'sushi',
  'sashimi',
  'dim sum',
  'dimsum',
  'hot pot',
  'szechuan',
  'peking duck',
  'pho',
  'vermicelli',
  'pad thai',
  'yakitori',
  'katsu',
  'tonkatsu',
  'tempura',
  'udon',
  'soba',
  'okonomiyaki',
  'curry',
  'onigiri',
  'takoyaki',
  'teriyaki',
  'sukiyaki',
  'shabu shabu',
  'shabushabu',
  'kaiseki',
  'omurice',
] as const;
